// Run: node tests/model.test.js   (pure logic of TalkToMeModel.js, no Quickshell needed)
const assert = require("assert")
const fs = require("fs")
const path = require("path")
const src = fs.readFileSync(path.join(__dirname, "..", "TalkToMeModel.js"), "utf8").replace(/^\.pragma library\n/, "")
const M = new Function(src + "; return { cleanId, clampInt, cleanText, keyAction, askKind, textResult, postponeResult, remainingText, statusJson, DEFAULTS }")()

assert.strictEqual(M.cleanId("abc123_-Z"), "abc123_-Z")
assert.strictEqual(M.cleanId("../etc"), "")
assert.strictEqual(M.cleanId("ab"), "")
assert.strictEqual(M.cleanId("a b c d"), "")
assert.strictEqual(M.cleanId(undefined), "")

assert.strictEqual(M.clampInt("7", 1, 10, 5), 7)
assert.strictEqual(M.clampInt("99", 1, 10, 5), 10)
assert.strictEqual(M.clampInt("-3", 1, 10, 5), 1)
assert.strictEqual(M.clampInt("x", 1, 10, 5), 5)

assert.strictEqual(M.cleanText("  hi\n\tthere ", 50), "hi there")
assert.strictEqual(M.cleanText("abcdefghij", 5), "abcd…")

assert.strictEqual(M.keyAction("countdown", "y", false), "human")
assert.strictEqual(M.keyAction("countdown", "Y", false), "human")
assert.strictEqual(M.keyAction("countdown", "n", false), "")
assert.strictEqual(M.keyAction("countdown", "", true), "end")
assert.strictEqual(M.keyAction("ask", "y", false), "yes")
assert.strictEqual(M.keyAction("ask", "N", false), "no")
assert.strictEqual(M.keyAction("ask", "?", false), "unsure")
assert.strictEqual(M.keyAction("ask", "/", false), "unsure")
assert.strictEqual(M.keyAction("ask", "t", false), "type")
assert.strictEqual(M.keyAction("ask", "x", false), "")
assert.strictEqual(M.keyAction("ask", "", true), "end")
assert.strictEqual(M.keyAction("idle", "y", false), "")

assert.strictEqual(M.askKind("text"), "text")
assert.strictEqual(M.askKind("whatever"), "choice")
assert.strictEqual(M.askKind(undefined), "choice")
assert.strictEqual(M.textResult("  it moved,\n but flickered "), "text:it moved, but flickered")
assert.strictEqual(M.textResult("   "), "")
assert.strictEqual(M.textResult("x".repeat(600)).length, 5 + 500)

assert.strictEqual(M.keyAction("ask", "p", false), "postpone")
assert.strictEqual(M.keyAction("countdown", "p", false), "postpone")
assert.strictEqual(M.postponeResult(" 15 "), "postpone:15")
assert.strictEqual(M.postponeResult("9999"), "postpone:240")
assert.strictEqual(M.postponeResult("0"), "")
assert.strictEqual(M.postponeResult("1.5"), "")
assert.strictEqual(M.postponeResult("abc"), "")
assert.strictEqual(M.postponeResult(""), "")

assert.strictEqual(M.remainingText(125), "2:05")
assert.strictEqual(M.remainingText(-4), "0:00")
console.log("ok")
